### ISSUE TITLE
Use as a Blackbox 

### ISSUE THREAD

**Issue by bsvdoom** [rtlopez/EspLogger#2]
Can this project used as a Blackbox logger? Especially for esp-fc :)

**Comment by rtlopez** [comment]
@bsvdoom Yes, I started it for this purpose, but abadoned it pretty quickly, when I figured out that standard `OpenLog` https://www.sparkfun.com/products/13712 device in connection with this firmware https://github.com/cleanflight/blackbox-firmware and modern SD card up to 32GB, can log data with 500k baud rate. It is enough to log 1k loop rate with full data and debug in current release 0.2.
